### ISSUE TITLE
HTML FILES NOT COMPLETE

### ISSUE THREAD

**Issue by Bawa009** [AhmedIsmailKhalid/IBM-Applied-AI-Specialization#3]
Hi, 
First of all thanks for all your hard work. I tried all the things you specified to the other guy and I downloaded all the files. For example, in Introduction to AI, week 1 HTML file consists of all the pages but for the rest of the weeks, the HTML files only showing only the first web page. I am attaching a pdf file as a proof.

Secondly, I couldn't see any .ipynb files in your folder.
Thanks
[screencapture-file-C-Users-hp-Desktop-cousera-IBM-Applied-AI-Specialization-master-Course-1-Introduction-to-Artificial-Intelligence-AI-Week-2-AI-Concepts-Terminology-and-Application-Areas-Week-2-Quiz-AI-Concepts-Termi.pdf](https://github.com/AhmedIsmailKhalid/IBM-Applied-AI-Specialization/files/5137228/screencapture-file-C-Users-hp-Desktop-cousera-IBM-Applied-AI-Specialization-master-Course-1-Introduction-to-Artificial-Intelligence-AI-Week-2-AI-Concepts-Terminology-and-Application-Areas-Week-2-Quiz-AI-Concepts-Termi.pdf)

**Comment by AhmedIsmailKhalid** [comment]
Hi, thanks for letting me know. So 1st of all I should mention that there are no ipynb files for Course 1, that is why you are not seeing any. However, I noticed that the readme does mention ipynb files which was a simple mistake of not deleting it (I use a template for my repositories and simply forgot to delete this part). I have updated the readme.

2nd, the files work perfectly for me, attaching a screenshot of the file when i open it below 

![image](https://user-images.githubusercontent.com/55996775/91466742-ff15f400-e8a8-11ea-8ce8-9a94eaa48416.png)

Have you tried download the files from the link below? If you and the problem was still persisting for you let me know and I'll see what can be done as a  The problem is that since it is a COMPLETE WEB PAGE other elements can be a pain in the ass. Initially, I tried a single webpage (.mthml) but that did not render it properly. 
https://github.com/AhmedIsmailKhalid/IBM-Applied-AI-Specialization/issues/2#issuecomment-658563243

**Comment by Bawa009** [comment]
Thank you so much. The new link was helpful although I think the problem is in web page rendering. I am currently checking the course 1. All files worked accept for week 4. But I think its some other issue and the files you provided are perfectly fine. I look for some other solution. If the problem persists, I will contact you without any hesitation.
Thank you once again for your work and help

**Comment by benharlucas** [comment]
> Hi, thanks for letting me know. So 1st of all I should mention that there are no ipynb files for Course 1, that is why you are not seeing any. However, I noticed that the readme does mention ipynb files which was a simple mistake of not deleting it (I use a template for my repositories and simply forgot to delete this part). I have updated the readme.
> 
> 2nd, the files work perfectly for me, attaching a screenshot of the file when i open it below
> 
> ![image](https://user-images.githubusercontent.com/55996775/91466742-ff15f400-e8a8-11ea-8ce8-9a94eaa48416.png)
> 
> Have you tried download the files from the link below? If you and the problem was still persisting for you let me know and I'll see what can be done as a The problem is that since it is a COMPLETE WEB PAGE other elements can be a pain in the ass. Initially, I tried a single webpage (.mthml) but that did not render it properly.
> [#2 (comment)](https://github.com/AhmedIsmailKhalid/IBM-Applied-AI-Specialization/issues/2#issuecomment-658563243)
> 
> EDIT :
> So the above referred link does not work anymore. I am reuploading the files and will provide the new link here. Try downloading from that and let me know if problem still persists.
> 
> [NEW LINK FOR FILES](https://mega.nz/folder/Ml5nxbLS#ZustF70Mt4xaSOEFxG6Sog)

Thank you so much Sir. Highly appreciated, Godbless for your hardwork and Keep Sharing ;)

**Comment by AhmedIsmailKhalid** [comment]
> Hi,
> First of all thanks for all your hard work. I tried all the things you specified to the other guy and I downloaded all the files. For example, in Introduction to AI, week 1 HTML file consists of all the pages but for the rest of the weeks, the HTML files only showing only the first web page. I am attaching a pdf file as a proof.
> 
> Secondly, I couldn't see any .ipynb files in your folder.
> Thanks
> [screencapture-file-C-Users-hp-Desktop-cousera-IBM-Applied-AI-Specialization-master-Course-1-Introduction-to-Artificial-Intelligence-AI-Week-2-AI-Concepts-Terminology-and-Application-Areas-Week-2-Quiz-AI-Concepts-Termi.pdf](https://github.com/AhmedIsmailKhalid/IBM-Applied-AI-Specialization/files/5137228/screencapture-file-C-Users-hp-Desktop-cousera-IBM-Applied-AI-Specialization-master-Course-1-Introduction-to-Artificial-Intelligence-AI-Week-2-AI-Concepts-Terminology-and-Application-Areas-Week-2-Quiz-AI-Concepts-Termi.pdf)

Hi Bawa. I tried the link and it still seems to work. As for the .ipynb files, there are none in that course that is why you cant see them
